"""Usage: python3 ci/icon/gen.py app/src/main/res <preview dir>

Generate the launcher icon as Android vector drawables, plus SVG previews built from the same
shapes. The art is a sticker: a smiling lime microphone with blushing cheeks, thick ink
outlines and a hard drop shadow, tilted a little, with sparkles, on an electric blue to hot
pink gradient. Kural means "voice", so the mic is the app's mascot."""
import os, sys

OUT_RES = sys.argv[1]          # app/src/main/res
OUT_PREVIEW = sys.argv[2]      # preview dir

BG_TOP, BG_BOTTOM = "#2D6BFF", "#FF3DA5"   # electric blue to hot pink
INK = "#14101F"                            # outlines, face and stand
LIME = "#C6FF3D"                           # the mic
BLUSH = "#FF7AB6"
SPARKLE = "#FFFFFF"
TILT = -8                                  # degrees: a playful lean
SHADOW = 7                                 # hard shadow offset, down and right
SCALE = 0.9                                # stays inside the adaptive icon's safe circle


def rrect(x, y, w, h, r):
    return (f"M{x+r},{y} h{w-2*r} a{r},{r} 0 0 1 {r},{r} v{h-2*r} a{r},{r} 0 0 1 {-r},{r} "
            f"h{-(w-2*r)} a{r},{r} 0 0 1 {-r},{-r} v{-(h-2*r)} a{r},{r} 0 0 1 {r},{-r} z")


def sparkle(cx, cy, r):
    k = r * 0.22
    return (f"M{cx},{cy-r} C{cx+k},{cy-k} {cx+k},{cy-k} {cx+r},{cy} C{cx+k},{cy+k} {cx+k},{cy+k} {cx},{cy+r} "
            f"C{cx-k},{cy+k} {cx-k},{cy+k} {cx-r},{cy} C{cx-k},{cy-k} {cx-k},{cy-k} {cx},{cy-r} Z")


def oval(cx, cy, rx, ry):
    return f"M{cx-rx},{cy} a{rx},{ry} 0 1 0 {2*rx},0 a{rx},{ry} 0 1 0 {-2*rx},0 z"


# Shapes: (kind, path, colour, stroke width, shadow?, role). Drawn on a 192 grid.
# role: "art" (tilted mic), "sparkle" (not tilted), "detail" (left out of the themed icon's fill).
CAPSULE = rrect(72, 34, 48, 82, 24)
STAND = ["M58,98 C58,142 134,142 134,98", "M96,132 L96,152", "M76,154 L116,154"]
shapes = []
for d in STAND:
    shapes.append(("stroke", d, INK, 9, False, "art"))  # no shadow: it would read as a second stand
shapes.append(("fill", CAPSULE, INK, 0, True, "shadow-only"))
shapes.append(("fill", CAPSULE, LIME, 0, False, "art"))
shapes.append(("stroke", CAPSULE, INK, 6, False, "art"))
shapes.append(("fill", rrect(83, 64, 7, 13, 3.5), INK, 0, False, "face"))      # eyes
shapes.append(("fill", rrect(102, 64, 7, 13, 3.5), INK, 0, False, "face"))
shapes.append(("stroke", "M83,87 C88,99 104,99 109,87", INK, 5, False, "face"))  # smile
shapes.append(("fill", oval(78, 86, 5, 4), BLUSH, 0, False, "detail"))           # cheeks
shapes.append(("fill", oval(114, 86, 5, 4), BLUSH, 0, False, "detail"))
shapes.append(("fill", sparkle(148, 44, 14), SPARKLE, 0, False, "sparkle"))
shapes.append(("fill", sparkle(42, 52, 8), SPARKLE, 0, False, "sparkle"))
shapes.append(("fill", sparkle(152, 142, 6), SPARKLE, 0, False, "sparkle"))


# ----- Android vector drawables -----

def vpath(kind, d, color, width):
    if kind == "fill":
        return f'<path android:fillColor="{color}" android:pathData="{d}" />'
    return (f'<path android:strokeColor="{color}" android:strokeWidth="{width}" '
            f'android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="{d}" />')


HEADER = ('<?xml version="1.0" encoding="utf-8"?>\n{comment}\n'
          '<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra}\n'
          '    android:width="108dp" android:height="108dp" android:viewportWidth="192" android:viewportHeight="192">\n')


def write(name, text):
    path = os.path.join(OUT_RES, "drawable", name)
    with open(path, "w") as f:
        f.write(text)
    print("wrote", path)


def foreground():
    tilt_open = f'        <group android:pivotX="96" android:pivotY="96" android:rotation="{TILT}">'
    lines = [f'    <group android:pivotX="96" android:pivotY="96" android:scaleX="{SCALE}" android:scaleY="{SCALE}">']
    # The hard shadow: every shadowed shape in ink, shifted.
    lines.append(f'        <group android:translateX="{SHADOW}" android:translateY="{SHADOW}">')
    lines.append(tilt_open.replace("        ", "            ", 1))
    for kind, d, color, width, shadow, role in shapes:
        if shadow:
            lines.append("                " + vpath(kind, d, INK, width))
    lines.append("            </group>")
    lines.append("        </group>")
    lines.append(tilt_open)
    for kind, d, color, width, shadow, role in shapes:
        if role in ("art", "face", "detail"):
            lines.append("            " + vpath(kind, d, color, width))
    lines.append("        </group>")
    for kind, d, color, width, shadow, role in shapes:
        if role == "sparkle":
            lines.append("        " + vpath(kind, d, color, width))
    lines.append("    </group>")
    return "\n".join(lines)


write("ic_launcher_foreground.xml",
      HEADER.format(comment="<!-- Launcher art: a smiling microphone sticker. Generated by ci/icon/gen.py. -->", extra="")
      + foreground() + "\n</vector>\n")

# Themed (monochrome) icon: one colour, so the mic is drawn as an outline with its face inside.
mono_lines = [f'    <group android:pivotX="96" android:pivotY="96" android:scaleX="{SCALE}" android:scaleY="{SCALE}">',
              f'        <group android:pivotX="96" android:pivotY="96" android:rotation="{TILT}">']
for d in STAND:
    mono_lines.append("            " + vpath("stroke", d, "#FFFFFF", 9))
mono_lines.append("            " + vpath("stroke", CAPSULE, "#FFFFFF", 8))
for kind, d, color, width, shadow, role in shapes:
    if role == "face":
        mono_lines.append("            " + vpath(kind, d, "#FFFFFF", width))
mono_lines.append("        </group>")
mono_lines.append("        " + vpath("fill", sparkle(148, 44, 14), "#FFFFFF", 0))
mono_lines.append("    </group>")
write("ic_launcher_monochrome.xml",
      HEADER.format(comment="<!-- Themed-icon version of the launcher art. Generated by ci/icon/gen.py. -->", extra="")
      + "\n".join(mono_lines) + "\n</vector>\n")

write("ic_launcher_background.xml",
      HEADER.format(comment="<!-- Generated by ci/icon/gen.py. -->", extra='\n    xmlns:aapt="http://schemas.android.com/aapt"')
      + f'''    <path android:pathData="M0,0h192v192h-192z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="192" android:endY="192"
                android:startColor="{BG_TOP}" android:endColor="{BG_BOTTOM}" />
        </aapt:attr>
    </path>
</vector>
''')


# ----- Previews: the icon in a squircle and a circle, and as a themed icon -----

def spath(kind, d, color, width):
    if kind == "fill":
        return f'<path fill="{color}" d="{d}"/>'
    return f'<path fill="none" stroke="{color}" stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round" d="{d}"/>'


def art_svg():
    shadow = "".join(spath(k, d, INK, w) for k, d, c, w, s, r in shapes if s)
    art = "".join(spath(k, d, c, w) for k, d, c, w, s, r in shapes if r in ("art", "face", "detail"))
    sparkles = "".join(spath(k, d, c, w) for k, d, c, w, s, r in shapes if r == "sparkle")
    return (f'<g transform="translate({SHADOW} {SHADOW}) rotate({TILT} 96 96)">{shadow}</g>'
            f'<g transform="rotate({TILT} 96 96)">{art}</g>{sparkles}')


def mono_svg(color):
    stand = "".join(spath("stroke", d, color, 9) for d in STAND)
    face = "".join(spath(k, d, color, w) for k, d, c, w, s, r in shapes if r == "face")
    return (f'<g transform="rotate({TILT} 96 96)">{stand}{spath("stroke", CAPSULE, color, 8)}{face}</g>'
            + spath("fill", sparkle(148, 44, 14), color, 0))


def icon_svg(mask, themed=False):
    clip = {"circle": '<circle cx="96" cy="96" r="96"/>', "squircle": '<rect width="192" height="192" rx="54"/>'}[mask]
    bg = '<rect width="192" height="192" fill="#E8E0FF"/>' if themed else '<rect width="192" height="192" fill="url(#bg)"/>'
    art = mono_svg("#2A1B5C") if themed else art_svg()
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192" width="192" height="192">'
            f'<defs><clipPath id="m">{clip}</clipPath>'
            f'<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{BG_TOP}"/>'
            f'<stop offset="1" stop-color="{BG_BOTTOM}"/></linearGradient></defs>'
            f'<g clip-path="url(#m)">{bg}<g transform="translate(96 96) scale({SCALE}) translate(-96 -96)">{art}</g></g></svg>')


os.makedirs(OUT_PREVIEW, exist_ok=True)
for mask in ("circle", "squircle"):
    with open(os.path.join(OUT_PREVIEW, f"icon-{mask}.svg"), "w") as f:
        f.write(icon_svg(mask))
with open(os.path.join(OUT_PREVIEW, "icon-themed.svg"), "w") as f:
    f.write(icon_svg("circle", themed=True))
print("previews in", OUT_PREVIEW)
