"""Usage: python3 ci/icon/gen.py app/src/main/res <preview dir>

Generate the launcher icon (a microphone sending out sound waves) as Android
vector drawables, plus SVG previews built from the same shapes."""
import os, sys

OUT_RES = sys.argv[1]          # app/src/main/res
OUT_PREVIEW = sys.argv[2]      # preview dir

def rrect(x, y, w, h, r):
    return (f"M{x+r},{y} h{w-2*r} a{r},{r} 0 0 1 {r},{r} v{h-2*r} a{r},{r} 0 0 1 {-r},{r} "
            f"h{-(w-2*r)} a{r},{r} 0 0 1 {-r},{-r} v{-(h-2*r)} a{r},{r} 0 0 1 {r},{-r} z")

BG_TOP, BG_BOTTOM = "#3B1F78", "#E0567A"   # deep violet to the app's coral
MIC = "#FFFFFF"
GRILLE = "#C9B8FF"
WAVE = "#FFD27A"

# Shapes: (kind, path, colour, alpha, stroke width). The artwork is drawn on a 192 grid.
shapes = []
def fill(d, color, alpha=1.0): shapes.append(("fill", d, color, alpha, 0))
def stroke(d, color, width, alpha=1.0): shapes.append(("stroke", d, color, alpha, width))

# Sound waves on both sides of the microphone: a voice going out.
stroke("M64,68 C54,78 54,102 64,112", WAVE, 8)
stroke("M128,68 C138,78 138,102 128,112", WAVE, 8)
stroke("M48,56 C32,74 32,106 48,124", WAVE, 7, 0.65)
stroke("M144,56 C160,74 160,106 144,124", WAVE, 7, 0.65)
# The microphone: capsule, grille, holder, stem and foot.
fill(rrect(78, 42, 36, 70, 18), MIC)
for y in (58, 68, 78):
    stroke(f"M88,{y} L104,{y}", GRILLE, 3.5)
stroke("M66,94 C66,126 126,126 126,94", MIC, 7)
stroke("M96,118 L96,138", MIC, 7)
stroke("M80,142 L112,142", MIC, 7)

GROUP = '<group android:pivotX="96" android:pivotY="96" android:scaleX="{s}" android:scaleY="{s}">'

def vector_path(kind, d, color, alpha, width, mono=False):
    if mono:
        color, alpha = "#FFFFFF", 1.0
    if kind == "fill":
        return f'        <path android:fillColor="{color}" android:fillAlpha="{alpha}" android:pathData="{d}" />'
    return (f'        <path android:strokeColor="{color}" android:strokeAlpha="{alpha}" android:strokeWidth="{width}" '
            f'android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="{d}" />')

HEADER = ('<?xml version="1.0" encoding="utf-8"?>\n{comment}\n'
          '<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra}\n'
          '    android:width="108dp" android:height="108dp" android:viewportWidth="192" android:viewportHeight="192">\n')

def write(name, text):
    path = os.path.join(OUT_RES, "drawable", name)
    with open(path, "w") as f:
        f.write(text)
    print("wrote", path)

SCALE = 0.9  # as big as fits: the outer waves stay inside the adaptive icon's safe circle

write("ic_launcher_foreground.xml",
      HEADER.format(comment="<!-- Launcher art: a microphone sending out sound waves. Generated by ci/icon/gen.py. -->", extra="")
      + "    " + GROUP.format(s=SCALE) + "\n"
      + "\n".join(vector_path(*s) for s in shapes) + "\n    </group>\n</vector>\n")

# Themed (monochrome) icon: the silhouette only, without the grille lines.
mono = [s for s in shapes if s[2] != GRILLE]
write("ic_launcher_monochrome.xml",
      HEADER.format(comment="<!-- Themed-icon silhouette of the launcher art. Generated by ci/icon/gen.py. -->", extra="")
      + "    " + GROUP.format(s=SCALE) + "\n"
      + "\n".join(vector_path(*s, mono=True) for s in mono) + "\n    </group>\n</vector>\n")

write("ic_launcher_background.xml",
      HEADER.format(comment="<!-- Generated by ci/icon/gen.py. -->", extra='\n    xmlns:aapt="http://schemas.android.com/aapt"')
      + f'''    <path android:pathData="M0,0h192v192h-192z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="192" android:endY="192"
                android:startColor="{BG_TOP}" android:endColor="{BG_BOTTOM}" />
        </aapt:attr>
    </path>
    <path android:pathData="M16,80 a80,80 0 1,0 160,0 a80,80 0 1,0 -160,0 z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="96" android:centerY="80" android:gradientRadius="80"
                android:startColor="#3DFFFFFF" android:endColor="#00FFFFFF" />
        </aapt:attr>
    </path>
</vector>
''')

# ----- Previews: the icon in a circle, a squircle, and as a themed icon. -----
def svg_path(kind, d, color, alpha, width, mono=False):
    if mono:
        color, alpha = "#2A1B5C", 1.0
    if kind == "fill":
        return f'<path fill="{color}" fill-opacity="{alpha}" d="{d}"/>'
    return (f'<path fill="none" stroke="{color}" stroke-opacity="{alpha}" stroke-width="{width}" '
            f'stroke-linecap="round" stroke-linejoin="round" d="{d}"/>')

def icon_svg(mask, themed=False):
    clip = {"circle": '<circle cx="96" cy="96" r="96"/>',
            "squircle": '<rect x="0" y="0" width="192" height="192" rx="54"/>'}[mask]
    if themed:
        bg = '<rect width="192" height="192" fill="#E4DBFF"/>'
        art = "".join(svg_path(*s, mono=True) for s in mono)
    else:
        bg = (f'<rect width="192" height="192" fill="url(#bg)"/>'
              f'<circle cx="96" cy="80" r="80" fill="url(#glow)"/>')
        art = "".join(svg_path(*s) for s in shapes)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192" width="192" height="192">'
            f'<defs><clipPath id="m">{clip}</clipPath>'
            f'<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{BG_TOP}"/>'
            f'<stop offset="1" stop-color="{BG_BOTTOM}"/></linearGradient>'
            f'<radialGradient id="glow" cx="0.5" cy="0.5" r="0.5"><stop offset="0" stop-color="#fff" stop-opacity="0.24"/>'
            f'<stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient></defs>'
            f'<g clip-path="url(#m)">{bg}<g transform="translate(96 96) scale({SCALE}) translate(-96 -96)">{art}</g></g></svg>')

os.makedirs(OUT_PREVIEW, exist_ok=True)
for mask in ("circle", "squircle"):
    with open(os.path.join(OUT_PREVIEW, f"icon-{mask}.svg"), "w") as f:
        f.write(icon_svg(mask))
with open(os.path.join(OUT_PREVIEW, "icon-themed.svg"), "w") as f:
    f.write(icon_svg("circle", themed=True))
print("previews in", OUT_PREVIEW)
