"""Usage: python3 ci/icon/gen.py app/src/main/res <preview dir>

Generate the launcher icon (a page of text giving off sound waves: a PDF read aloud) as
Android vector drawables, plus an SVG preview built from the same shapes."""
import math, os, sys

OUT_RES = sys.argv[1]
OUT_PREVIEW = sys.argv[2]

BG_TOP, BG_BOTTOM = "#14324F", "#1C8C7A"   # night blue to the app's teal
PAGE, FOLD, INK = "#FFF8EC", "#E8D9BC", "#C9A86A"
WAVE = "#FFB547"                           # the app's amber

# (kind, path, colour, alpha, stroke width), drawn on a 108 grid (the adaptive icon canvas).
shapes = []
def fill(d, color, alpha=1.0): shapes.append(("fill", d, color, alpha, 0))
def stroke(d, color, width, alpha=1.0): shapes.append(("stroke", d, color, alpha, width))

X0, Y0, W, H, R, F = 24, 28, 32, 52, 4, 9   # the page, with a folded top-right corner
fill(f"M{X0+R},{Y0} h{W-R-F} l{F},{F} v{H-F-R} a{R},{R} 0 0 1 -{R},{R} h-{W-2*R} "
     f"a{R},{R} 0 0 1 -{R},-{R} v-{H-2*R} a{R},{R} 0 0 1 {R},-{R} z", PAGE)
fill(f"M{X0+W-F},{Y0} v{F-2} a2,2 0 0 0 2,2 h{F-2} z", FOLD)
for i, y in enumerate([44, 51, 58, 65, 72]):
    stroke(f"M{X0+6},{y} H{X0 + (W - 6 if i % 2 == 0 else W - 11)}", INK, 3.2)

CX, CY = 60, 54
for r, a in [(9, 1.0), (16, 0.85), (23, 0.7)]:
    dx, dy = r * math.cos(math.radians(45)), r * math.sin(math.radians(45))
    stroke(f"M{CX+dx:.2f},{CY-dy:.2f} A{r},{r} 0 0 1 {CX+dx:.2f},{CY+dy:.2f}", WAVE, 4.5, a)

def vector(items, mono=False):
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Launcher art: a page giving off sound waves. Generated by ci/icon/gen.py. -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">']
    for kind, d, color, alpha, width in items:
        if mono:
            if color == "#000000" or color in (INK, FOLD):
                continue
            color, alpha = "#FFFFFF", 1.0
        if kind == "fill":
            out.append(f'    <path android:fillColor="{color}" android:fillAlpha="{alpha}" android:pathData="{d}" />')
        else:
            out.append(f'    <path android:strokeColor="{color}" android:strokeAlpha="{alpha}" android:strokeWidth="{width}" '
                       f'android:strokeLineCap="round" android:pathData="{d}" />')
    out.append('</vector>')
    return "\n".join(out) + "\n"

background = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by ci/icon/gen.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="108" android:endY="108"
                android:startColor="{BG_TOP}" android:endColor="{BG_BOTTOM}" />
        </aapt:attr>
    </path>
</vector>
'''

drawable = os.path.join(OUT_RES, "drawable")
open(os.path.join(drawable, "ic_launcher_background.xml"), "w").write(background)
open(os.path.join(drawable, "ic_launcher_foreground.xml"), "w").write(vector(shapes))
open(os.path.join(drawable, "ic_launcher_monochrome.xml"), "w").write(vector(shapes, mono=True))

# Status-bar icon: the same idea on a 24 grid, in white.
stat = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Notification icon: a page giving off sound waves. Generated by ci/icon/gen.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">
    <path android:fillColor="#FFFFFFFF" android:pathData="M4,3h7l3,3v14a1,1 0 0 1 -1,1h-9a1,1 0 0 1 -1,-1v-16a1,1 0 0 1 1,-1z" />
    <path android:strokeColor="#FFFFFFFF" android:strokeWidth="1.8" android:strokeLineCap="round" android:pathData="M16.5,9.5 A3.5,3.5 0 0 1 16.5,14.5" />
    <path android:strokeColor="#FFFFFFFF" android:strokeWidth="1.8" android:strokeLineCap="round" android:pathData="M19,7 A7,7 0 0 1 19,17" />
</vector>
'''
open(os.path.join(drawable, "ic_stat_vaasi.xml"), "w").write(stat)

os.makedirs(OUT_PREVIEW, exist_ok=True)
def svg(items, bg=True):
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="432" height="432">']
    parts.append(f'<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{BG_TOP}"/>'
                 f'<stop offset="1" stop-color="{BG_BOTTOM}"/></linearGradient>'
                 f'<clipPath id="c"><circle cx="54" cy="54" r="54"/></clipPath></defs><g clip-path="url(#c)">')
    if bg: parts.append('<rect width="108" height="108" fill="url(#g)"/>')
    for kind, d, color, alpha, width in items:
        if kind == "fill":
            parts.append(f'<path d="{d}" fill="{color}" fill-opacity="{alpha}"/>')
        else:
            parts.append(f'<path d="{d}" fill="none" stroke="{color}" stroke-opacity="{alpha}" stroke-width="{width}" stroke-linecap="round"/>')
    parts.append('<circle cx="54" cy="54" r="33" fill="none" stroke="#ff00ff" stroke-opacity="0.0"/></g></svg>')
    return "".join(parts)
open(os.path.join(OUT_PREVIEW, "icon.svg"), "w").write(svg(shapes))
